import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from "@/components/layout/Header";
import './globals.css'


const digiHamishe = localFont({
  src: [
    {
      path: "./fonts/digi-hamishe-regular.ttf",
      weight: "400",
      // style: "normal",
    },
    {
      path: "./fonts/digi-hamishe-bold.ttf",
      weight: "700",
      // style: "normal",
    },
  ],
  // variable: "--font-digi-hamishe",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` h-full antialiased ${digiHamishe.className}`}
      dir="rtl"
    >
      <body className="min-h-full flex flex-col">
        <Header />
        {children}
      </body>

    </html>
  );
}
